routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ROUTE PAR DEFAUT
// PATTERN : /
// CTRL : PagesController
// ACTION : Show

Route::get('/', 'PagesController@show')->defaults('page', 1)->name('homepage');

// ROUTE DU DETAIL D'UNE PAGE
// PATTERN : /pages/id/slug.html
// CTRL : PagesController
// ACTION : Show

Route::get('/pages/{page}/{slug}.html', 'PagesController@show')
->where(['page' => '[1-9][0-9]*',
         'slug' => '[a-z0-9]+[a-z0-9\-]*[a-z0-9]'])
->name('pages.show');

//ROUTES DES CREATURES

Route::prefix('creatures')->name('creatures.')->group(function () {

  // ROUTE DU DETAIL D'UNE CREATURE
  // PATTERN : /creatures/id/slug.html
  // CTRL : CreaturesController
  // ACTION : Show

  Route::get('{creature}/{slug}.html', 'CreaturesController@show')
  ->where(['creature' => '[1-9][0-9]*',
           'slug' => '[a-z0-9]+[a-z0-9\-]*[a-z0-9]'])
  ->name('show');

  // ROUTE DE LA RECHERCHE SUR LES CREATURES
  // PATTERN : /creatures/search.html?search=...
  // CTRL : CreaturesController
  // ACTION : Search

  Route::get('search.html', 'CreaturesController@search')
  ->name('search');
});

//ROUTES DES FILMS

Route::prefix('films')->name('films.')->group(function () {

  // ROUTE DU DETAIL D'UN FILM
  // PATTERN : /films/id/slug.html
  // CTRL : FilmsController
  // ACTION : Show

  Route::get('{film}/{slug}.html', 'FilmsController@show')
  ->where(['film' => '[1-9][0-9]*',
           'slug' => '[a-z0-9]+[a-z0-9\-]*[a-z0-9]'])
  ->name('show');

  // ROUTE DE L'AJOUT D'UN FILM
  // PATTERN : /films/add.html
  // CTRL : FilmsController
  // ACTION : Create

  Route::get('add.html', 'FilmsController@create')
  ->name('create');

  // ROUTE DE L'INSERT D'UN FILM
  // PATTERN : /films [POST]
  // CTRL : FilmsController
  // ACTION : store

  Route::post('', 'FilmsController@store')
  ->name('store');

  // ROUTE DE L'EDIT D'UN FILM
  // PATTERN : films/id/slug/edit.html
  // CTRL : FilmsController
  // ACTION : edit

  Route::get('{film}/{slug}/edit.html', 'FilmsController@edit')
  ->where(['film' => '[1-9][0-9]*',
           'slug' => '[a-z0-9]+[a-z0-9\-]*[a-z0-9]'])
  ->name('edit');

  // ROUTE DE L'UPDATE D'UN FILM
  // PATTERN : /films/id/slug.html [PATCH]
  // CTRL : FilmsController
  // ACTION : update

  Route::patch('{film}/{slug}.html', 'FilmsController@update')
  ->where(['film' => '[1-9][0-9]*',
           'slug' => '[a-z0-9]+[a-z0-9\-]*[a-z0-9]'])
  ->name('update');

  // ROUTE DE LA SUPPRESSION D'UN FILM
  // PATTERN : /films/id/slug.html  [DELETE]
  // CTRL : FilmsController
  // ACTION : destroy

  Route::delete('{film}/{slug}.html', 'FilmsController@destroy')
  ->where(['film' => '[1-9][0-9]*',
          'slug' => '[a-z0-9]+[a-z0-9\-]*[a-z0-9]'])
  ->name('destroy');

});


// ROUTE DU DETAIL D'UN TAG
// PATTERN : /tags/id/slug.html
// CTRL : TagsController
// ACTION : Show

Route::get('/tags/{tag}/{slug}.html', 'TagsController@show')
->where(['tag' => '[1-9][0-9]*',
        'slug' => '[a-z0-9]+[a-z0-9\-]*[a-z0-9]'])
->name('tags.show');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CreaturesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use App\Http\Models\Creature;

class CreaturesController extends Controller
{
  /**
   * Affiche le détail d'une créature
   * @param  Creature $creature
   * @return vue creatures.show
   */
  public function show(Creature $creature) {
    return View::make('creatures.show', compact('creature'));
  }

  /**
   * Recherche sur les créatures
   * @param  Request $request
   * @return vue creatures.search
   */
  public function search(Request $request) {
    $search = request()->input('search');
    $creatures = Creature::where('nom', 'like', '%' . "%$search%")->get();
    return View::make('creatures.search', compact('creatures'));

  }

}

app/Http/Controllers/FilmsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Str;
use App\Http\Models\Film;

class FilmsController extends Controller
{
  /**
   * Affiche le détail d'un film
   * @param  Film   $film
   * @return vue films.show
   */
   public function show(Film $film) {
     return View::make('films.show', compact('film'));
   }

  /**
   * Affiche le formulaire d'ajout d'un film
   * @return vue films.create
   */
   public function create() {
     return View::make('films.create');
   }

   /**
    * Insert du film dans la db
    * @param  Request $request
    * @return redirection vers la liste des films
    */
   public function store(Request $request) {
     Film::create($request->all());
     return redirect()->route('pages.show', ['page' => 3,
                                             'slug' => 'les-films']);
   }

   /**
    * Affiche le formulaire de modification d'un film
    * @param  Film   $film
    * @return vue films.edit
    */
   public function edit(Film $film) {
     return View::make('films.edit', compact('film'));
   }
   /**
    * Update du film dans la db
    * @param  Request $request
    * @param  Film    $film
    * @return redirection vers le détail du film
    */
   public function update(Request $request, Film $film) {
     $film->update($request->all());
     return redirect()->route('films.show', ['film' => $film->id,
                                             'slug' => Str::slug($film->titre)]);
   }

   /**
    * Suppression d'un film de la db
    * @param  Film   $film
    * @return redirection vers la liste des films
    */
   public function destroy(Film $film) {
     $film->destroy($film->id);
     return redirect()->route('pages.show', ['page' => 3,
                                             'slug' => 'les-films']);
   }
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use App\Http\Models\Page;
use App\Http\Models\Film;
use App\Http\Models\Creature;

class PagesController extends Controller
{
 /**
  * Affiche le détail d'une page
  * @param  Page   $page
  * @return vue pages.show
  */
  public function show(Page $page) {
    if ($page->id ===1):
      $creatures = Creature::orderBy('created_at', 'DESC')->take(2)->get();
      return View::make('pages.show', compact('page', 'creatures'));
    elseif ($page->id === 2):
      $creatures = Creature::all();
      return View::make('pages.show', compact('page', 'creatures'));
    elseif ($page->id === 3):
      $films = Film::all();
      return View::make('pages.show', compact('page', 'films'));
    endif;
    return View::make('pages.show', compact('page'));
  }

}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use App\Http\Models\Tag;

class TagsController extends Controller
{

    /**
     * Affiche le détail d'un tag
     * @param  Tag    $tag
     * @return vue tags.show
     */
    public function show(Tag $tag) {
      return View::make('tags.show', compact('tag'));
    }
}

resources/views/creatures/index.blade.php
{{--
  ./resources/views/creatures/index.blade.php
  Variables disponibles :
      - $creatures array(Creature)
 --}}

@foreach ($creatures as $creature)
<!-- Project One -->
<div class="row">
  <div class="col-md-4">
    <a href="#">
      <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/' . $creature->image)}}" alt="">
    </a>
  </div>
  <div class="col-md-8">
    <h3>{{ $creature->nom }}</h3>
    <p class="lead">
      dans
      <a href="{{ route('films.show', [
        'film' => $creature->filmData->id,
        'slug' => Str::slug($creature->filmData->titre)
        ])}}">{{ $creature->filmData->titre }}</a>
      le {{ \Carbon\Carbon::parse($creature->created_at)->format('d/m/Y') }}
    </p>
    <p>{{ $creature->texteLead }}</p>

    <div>
      <a class="btn btn-primary" href="{{ route('creatures.show', [
          'creature' => $creature->id,
          'slug' => Str::slug($creature->nom)
        ]) }}">Voir la créature</a>

    </div>
    <hr/>
    <ul class="list-inline tags">
      @foreach($creature->tags as $tag)
      <li><a href="{{ route('tags.show', [
          'tag' => $tag->id,
          'slug' => Str::slug($tag->nom)
        ]) }}" class="btn btn-default btn-xs">{{ $tag->nom }}</a></li>
      @endforeach
    </ul>
  </div>
</div>
<!-- /.row -->

<hr>
@endforeach

resources/views/creatures/latest.blade.php
{{--
  ./resources/views/creatures/latest.blade.php
  Variables disponibles :
      - $creatures array(Creature)
 --}}

<!-- Title -->
<h2 class="mt-4">Dernieres créatures</h2>

<hr>
@foreach ($creatures as $creature)
<!-- Project One -->
<div class="row">
  <div class="col-md-4">
    <a href="#">
      <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/' . $creature->image)}}" alt="">
    </a>
  </div>
  <div class="col-md-8">
    <h3>{{ $creature->nom }}</h3>
    <p class="lead">
      dans
      <a href="{{ route('films.show', [
        'film' => $creature->filmData->id,
        'slug' => Str::slug($creature->filmData->titre)
        ])}}">{{ $creature->filmData->titre }}</a>
      le {{ \Carbon\Carbon::parse($creature->created_at)->format('d/m/Y') }}
    </p>
    <p>{{ $creature->texteLead }}</p>

    <div>
      <a class="btn btn-primary" href="{{ route('creatures.show', [
          'creature' => $creature->id,
          'slug' => Str::slug($creature->nom)
        ]) }}">Voir la créature</a>

    </div>
    <hr/>
    <ul class="list-inline tags">
      @foreach($creature->tags as $tag)
      <li><a href="{{ route('tags.show', [
          'tag' => $tag->id,
          'slug' => Str::slug($tag->nom)
        ]) }}" class="btn btn-default btn-xs">{{ $tag->nom }}</a></li>
      @endforeach
    </ul>
  </div>
</div>
<!-- /.row -->

<hr>
@endforeach

resources/views/creatures/search.blade.php
{{--
  ./resources/views/creatures/searchresults.blade.php
  Variables disponibles :
      - $creatures array(Creature)
 --}}

 @extends('template.defaut')

 @section('title')
   Résultats de la recherche : {{ request()->input('search') }}
 @endsection

 @section('content1')

   <!-- Page Heading -->

   <!-- Title -->
   <h1 class="mt-4">Résultats de la recherche : <small>{{ request()->input('search') }}</small></h1>

   <hr>

   @foreach ($creatures as $creature)
     <!-- Project One -->
     <div class="row">
       <div class="col-md-4">
         <a href="#">
           <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/' . $creature->image)}}" alt="">
         </a>
       </div>
       <div class="col-md-8">
         <h3>{{ $creature->nom }}</h3>
         <p class="lead">
           dans
           <a href="{{ route('films.show', [
             'film' => $creature->filmData->id,
             'slug' => Str::slug($creature->filmData->titre)
             ])}}">{{ $creature->filmData->titre }}</a>
           le {{ \Carbon\Carbon::parse($creature->created_at)->format('d/m/Y') }}
         </p>
         <p>{{ $creature->texteLead }}</p>

         <div>
           <a class="btn btn-primary" href="{{ route('creatures.show', [
               'creature' => $creature->id,
               'slug' => Str::slug($creature->nom)
             ]) }}">Voir la créature</a>

         </div>
         <hr/>
         <ul class="list-inline tags">
           @foreach($creature->tags as $tag)
           <li><a href="#" class="btn btn-default btn-xs">{{ $tag->nom }}</a></li>
           @endforeach
         </ul>
       </div>
     </div>
     <!-- /.row -->

     <hr>
   @endforeach
 @endsection

resources/views/creatures/show.blade.php
{{--
  ./resources/views/creatures/show.blade.php
  - Variables disponibles
    $creature Creature
 --}}

@extends('template.defaut')

@section('title')
  {{ $creature->nom }}
@endsection

@section('content1')

  <!-- Page Heading -->

  <!-- Title -->
  <h1 class="mt-4">{{ $creature->nom }}</h1>
  <p class="lead">
    dans
    <a href="{{ route('films.show', [
      'film' => $creature->filmData->id,
      'slug' => Str::slug($creature->filmData->titre)
      ])}}">{{ $creature->filmData->titre }}</a>
    le {{ \Carbon\Carbon::parse($creature->created_at)->format('d/m/Y') }}
  </p>

  <hr>

  <!-- Project One -->
  <div class="row">
    <div class="col-md-6">
      <a href="#">
        <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/' . $creature->image)}}" alt="">
      </a>
    </div>
    <div class="col-md-6">
      <p class="lead">{{ $creature->texteLead }}</p>
      <hr/>
      <p>{{ $creature->texteSuite }}</p>

      <hr/>
      <ul class="list-inline tags">
        @foreach($creature->tags as $tag)
        <li><a href="{{ route('tags.show', [
            'tag' => $tag->id,
            'slug' => Str::slug($tag->nom)
          ]) }}" class="btn btn-default btn-xs">{{ $tag->nom }}</a></li>
        @endforeach
      </ul>
    </div>
  </div>
  <!-- /.row -->
  <hr>

@endsection

resources/views/films/create.blade.php
{{--
  ./resources/views/films/create.blade.php
  - Variables disponibles
    /
 --}}

@extends('template.defaut')

@section('title')
  Ajouter un film
@endsection

@section('content1')
<h1 class="mt-4">Ajouter un Film</h1>

<form action="{{ route('films.store') }}" method="POST">
    @csrf
  <div class="form-group">
    <label for="titre">Titre</label>
    <input name="titre" type="text" class="form-control" />
  </div>
  <div class="form-group">
    <label for="synopsis">Synopsis</label>
    <textarea name="synopsis" rows="8" cols="80" class="form-control"></textarea>
  </div>
  <div class="form-group">
    <input type="submit" class="btn btn-primary" />
  </div>
</form>

<!-- /.row -->
<hr>
@endsection

resources/views/films/edit.blade.php
{{--
  ./resources/views/films/edit.blade.php
  - Variables disponibles
    $film Film
 --}}

 @extends('template.defaut')

 @section('title')
   Modifier un film
 @endsection

 @section('content1')

   <h1 class="mt-4">Modifier un Film</h1>

   <form action="{{ route('films.update', [
       'film' => $film->id,
       'slug' => Str::slug($film->titre)
     ]) }}" method="POST">
       @csrf
       {{ method_field('PATCH') }}
     <div class="form-group">
       <label for="titre">Titre</label>
       <input name="titre" type="text" class="form-control" value="{{ $film->titre }}"/>
     </div>
     <div class="form-group">
       <label for="synopsis">Synopsis</label>
       <textarea name="synopsis" rows="8" cols="80" class="form-control">
         {{ $film->synopsis }}
       </textarea>
     </div>
     <div class="form-group">
       <input type="submit" class="btn btn-primary" />
     </div>
   </form>

   <!-- /.row -->
   <hr>


@endsection

resources/views/films/index.blade.php
{{--
  ./resources/views/films/index.blade.php
  Variables disponibles :
      - $films array(Film)
 --}}

<a class="btn btn-primary" href="{{ route('films.create') }}">Ajouter un film</a>
<hr/>

@foreach ($films as $film)
<!-- Project One -->
<div class="row">
  <div class="col-md-4">
    <a href="#">
      <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('../public/images/' . $film->image) }}" alt="">
    </a>
  </div>
  <div class="col-md-8">
    <h3>{{ $film->titre }}</h3>
    <p>{{ $film->synopsis}}</p>
    <a class="btn btn-primary" href="{{ route('films.show', [
        'film' => $film->id,
        'slug' => Str::slug($film->titre)
      ]) }}">Voir les détails du film</a>
    <hr/>
  </div>
</div>
<hr/>
@endforeach

resources/views/films/show.blade.php
{{--
  ./resources/views/films/show.blade.php
  - Variables disponibles
    $film Film
 --}}

@extends('template.defaut')

@section('title')
  {{ $film->titre }}
@endsection

@section('content1')
<!-- Page Heading -->

<!-- Title -->
<h1 class="mt-4">{{ $film->titre}}</h1>

<hr>

<!-- Project One -->
<div class="row">
  <div class="col-md-4">
    <a href="#">
      <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/' . $film->image)}}" alt="">
    </a>
  </div>
  <div class="col-md-8">
    <p class="lead">{{ $film->synopsis }}</p>
    <hr/>
    <h2>Créatures du film</h2>
    <ul>
      @foreach ($film->creatures as $creature)
        <li><a href="{{ route('creatures.show', [
            'creature' => $creature->id,
            'slug' => Str::slug($creature->nom)
          ]) }}">{{ $creature->nom }}</a></li>
      @endforeach
    </ul>
    <hr/>
      <a class="btn btn-primary" href="{{ route('films.edit', [
          'film' => $film->id,
          'slug' => Str::slug($film->titre)
        ]) }}">Modifier</a>
    <form style="display: inline-block;" method="POST" action="{{ route('films.destroy', [
          'film' => $film->id,
          'slug' => Str::slug($film->titre)
        ]) }}">
    {{ csrf_field() }}
    {{ method_field('DELETE') }}
    <div class="form-group">
      <input type="submit" class="btn btn-secondary" value="Supprimer">
    </div>
    </form>
    <hr />

  </div>
</div>
<!-- /.row -->
<hr>
@endsection

resources/views/pages/_menu.blade.php
{{--
  ./resources/views/pages/_menu.blade.php
  variables disponibles :
      - $pages array(Page)
 --}}

<ul class="navbar-nav ml-auto">
  @foreach ($pages as $page)
  <li class="nav-items">
    <a class="nav-link {{ request()->segment(2) == $page->id ? 'active' : '' }}" href="{{ route('pages.show', [
        'page' => $page->id,
        'slug' => Str::slug($page->titre)
      ]) }}">
      {{ $page->titre }}
    </a>
  </li>
  @endforeach
</ul>

resources/views/pages/show.blade.php
{{--
  ./resources/views/pages/show.blade.php
  variables disponibles :
      - $page Page
 --}}

@extends('template.defaut')

@section('title')
  {{ $page->titre }}
@endsection

@section('content1')
<!-- Page Heading -->

<!-- Title -->
<h1 class="mt-4">{{ $page->titre }}</h1>

<hr>


<!-- Post Content -->
<p class="lead">{{ $page->texte }}</p>


<hr>


@if ($page->id === 1)

  @include('creatures.latest')

@elseif ($page->id === 2)

  @include('creatures.index')

@elseif ($page->id === 3)

  @include('films.index')

@endif


@endsection

resources/views/tags/_index.blade.php
{{--
  ./resources/views/tags/_index.blade.php
  variables disponibles :
      - $tags array(Tag)
 --}}

<ul class="list-unstyled mb-0">
  @foreach ($tags as $tag)
  <li>
    <a href="{{ route('tags.show', [
        'tag' => $tag->id,
        'slug' => Str::slug($tag->nom)
      ]) }}">
      {{ $tag->nom }}
    </a>
  </li>
  @endforeach
</ul>

resources/views/tags/show.blade.php
{{--
  ./resources/views/tags/show.blade.php
  - Variables disponibles
    $tag Tag
 --}}

@extends ('template.defaut')

@section('title')
  {{ $tag->nom }}
@endsection

@section('content1')
<!-- Page Heading -->

<!-- Title -->
<h1 class="mt-4">Résultats pour le tag : <small>{{ $tag->nom }}</small></h1>

<hr>
@foreach ($tag->creatures as $creature)
  <!-- Project One -->
  <div class="row">
    <div class="col-md-4">
      <a href="#">
        <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/' . $creature->image)}}" alt="">
      </a>
    </div>
    <div class="col-md-8">
      <h3>{{ $creature->nom }}</h3>
      <p class="lead">
        dans
        <a href="{{ route('films.show', [
          'film' => $creature->filmData->id,
          'slug' => Str::slug($creature->filmData->titre)
          ])}}">{{ $creature->filmData->titre }}</a>
        le {{ \Carbon\Carbon::parse($creature->created_at)->format('d/m/Y') }}
      </p>
      <p>{{ $creature->texteLead }}</p>

      <div>
        <a class="btn btn-primary" href="{{ route('creatures.show', [
            'creature' => $creature->id,
            'slug' => Str::slug($creature->nom)
          ]) }}">Voir la créature</a>

      </div>
      <hr/>
      <ul class="list-inline tags">
        @foreach($creature->tags as $tag)
        <li><a href="#" class="btn btn-default btn-xs">{{ $tag->nom }}</a></li>
        @endforeach
      </ul>
    </div>
  </div>
  <!-- /.row -->

  <hr>
@endforeach
@endsection

resources/views/template/defaut.blade.php
<!DOCTYPE html>
<html lang="en">

  <head>
    @include('template.partials._head')
  </head>

  <body>

    <!-- Navigation -->
  @include('template.partials._nav')

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          @yield('content1')

        </div>

        <!-- Sidebar Widgets Column -->
      @include('template.partials._sidebar')

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    @include('template.partials._footer')

    <!-- Scripts -->
    @include('template.partials._scripts')

  </body>

</html>

resources/views/template/partials/_footer.blade.php
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; IEPS 2017 <!-- | <a href="login.html">Administration</a>--></p>
  </div>
  <!-- /.container -->
</footer>

resources/views/template/partials/_head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title>Vintage Sci-Fi - @yield('title')</title>

<!-- Bootstrap core CSS -->
<link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{{ asset('css/blog-post.css') }}" rel="stylesheet">

resources/views/template/partials/_nav.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{{ Route('homepage') }}">Vintage Sci-Fi - Les Créatures du Futur</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      @include('pages._menu')
    </div>
  </div>
</nav>

resources/views/template/partials/_scripts.blade.php
<!-- Bootstrap core JavaScript -->
<script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('vendor/app.js') }}"></script>
<script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

resources/views/template/partials/_sidebar.blade.php
<div class="col-md-4">

  <!-- Search Widget -->
  <div class="card my-4">
    <h5 class="card-header">Rechercher une créature</h5>
    <div class="card-body">
      <form class="" action="{{ route('creatures.search') }}" method="get">
        <div class="input-group">
          <input name="search" value="{{ request()->input('search') }}" type="text" class="form-control" placeholder="Mot-clé">
          <span class="input-group-btn">
            <button class="btn btn-secondary" type="submit">Go!</button>
          </span>
        </div>
      </form>
    </div>
  </div>

  <!-- Categories Widget -->
  <div class="card my-4">
    <h5 class="card-header">Tags</h5>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-12">
          @include('tags._index')
        </div>

      </div>
    </div>
  </div>


</div>